### ISSUE TITLE
数据的索引有问题

### ISSUE THREAD

**Issue by caojiangege** [m-lyon/dmri-pcconv#1]
亲爱的教授：
   我根据你的步骤进行了数据的处理，但是他还是包了错。很期待你的回复
----------------------------------------
0 | pccnn | PCCNN | 765 K  | train
----------------------------------------
765 K     Trainable params
0         Non-trainable params
765 K     Total params
3.061     Total estimated model params size (MB)
Sanity Checking: |                                        | 0/? [00:00<?, ?it/s]Traceback (most recent call last):
  File "/data_new/cj/dmri_pcconv/train.py", line 56, in <module>
    trainer.fit(model, data_module)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 543, in fit
    call._call_and_handle_interrupt(
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 986, in _run
    results = self._run_stage()
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1028, in _run_stage
    self._run_sanity_check()
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1057, in _run_sanity_check
    val_loop.run()
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 128, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/loops/fetchers.py", line 133, in __next__
    batch = super().__next__()
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/loops/fetchers.py", line 60, in __next__
    batch = next(self.iterator)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/utilities/combined_loader.py", line 341, in __next__
    out = next(self._iterator)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/utilities/combined_loader.py", line 142, in __next__
    out = next(self.iterators[0])
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/dmri_pcconv/core/training.py", line 211, in __getitem__
    return self._get_patch_data(subject, local_index)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/dmri_pcconv/core/training.py", line 223, in _get_patch_data
    qspace_index = self._get_qspace_index(subject)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/dmri_pcconv/core/training.py", line 240, in _get_qspace_index
    return self.qspace_sampler.get_subject_sample(
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/dmri_pcconv/core/qspace.py", line 253, in get_subject_sample
    q_in_order, q_out_order = self._get_subject_sample(
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/dmri_pcconv/core/qspace.py", line 239, in _get_subject_sample
    orders[shell] = self._get_bvec_sample_order(
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/dmri_pcconv/core/qspace.py", line 203, in _get_bvec_sample_order
    order[0] = idx_map[start]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by m-lyon** [comment]
What `q_in_min` and `q_in_max` values are you using to instantiate the `QSpaceInfo`? What is the shape of the bvecs that you are loading?

**Comment by caojiangege** [comment]
q_in_min=6,q_in_max=20,我在hcp上选了5个b1000,5个b2000,5个b3000, bvecs的shape为(3, 15)

**Comment by caojiangege** [comment]
我是根据你上面的方法来进行操作的。QSpaceInfo我没对其进行修改

**Comment by caojiangege** [comment]
麻烦能不能帮我进行复现。

**Comment by m-lyon** [comment]
> q_in_min=6,q_in_max=20,我在hcp上选了5个b1000,5个b2000,5个b3000, bvecs的shape为(3, 15)

Okay, the problem is that `q_in_min` and `q_in_max` refer to the minimum and maximum `q_in` size that can be sampled **per shell**. Since each of the shells you provided have a size less than this range  (5 in this case), this has caused an indexing error. To ensure this error doesn't happen, you should provide data that have more than `q_in_max` b-vectors within **each** shell. For example if you had 30 b-vectors in each of the `b = 1000`, `b = 2000`, and `b = 3000` shells.

As an explainer: the training implemented here will, for each training input, randomly sample a set of b-vectors of a size between the `q_in_min` and `q_in_max` within a randomly sampled shell. For example one training input might have a set of 8 b-vectors in the shell `b = 1000`, then the next might have a set of 15 in the shell `b = 2000`. The corresponding training output is similar, but it's size is set by `q_out`, and the shell is similarly randomly sampled.

**Comment by caojiangege** [comment]
Dear professor:
  谢谢你的回答，索引的问题我通过你的回答已经解决了，但是他有报了新的问题return self._get_patch_data(subject, local_index)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/dmri_pcconv/core/training.py", line 224, in _get_patch_data
    patch_in, patch_out = self.patcher.get_patch(
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/dmri_pcconv/core/patcher.py", line 87, in get_patch
    patch = self._patcher.get_patch(
RuntimeError: Fortran data order extraction not currently implemented.   请问这个错误是什么导致的

**Comment by caojiangege** [comment]
Dear professor:
  我又按照流程走了一遍 还是报上面的错误，是否数据的预处理漏了一些

**Comment by caojiangege** [comment]
0 | pccnn | PCCNN | 765 K  | train
----------------------------------------
765 K     Trainable params
0         Non-trainable params
765 K     Total params
3.061     Total estimated model params size (MB)
Sanity Checking: |                                        | 0/? [00:00<?, ?it/s]Traceback (most recent call last):
  File "/data_new/cj/dmri_pcconv/train.py", line 56, in <module>
    trainer.fit(model, data_module)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 543, in fit
    call._call_and_handle_interrupt(
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 986, in _run
    results = self._run_stage()
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1028, in _run_stage
    self._run_sanity_check()
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1057, in _run_sanity_check
    val_loop.run()
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 128, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/loops/fetchers.py", line 133, in __next__
    batch = super().__next__()
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/loops/fetchers.py", line 60, in __next__
    batch = next(self.iterator)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/utilities/combined_loader.py", line 341, in __next__
    out = next(self._iterator)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/utilities/combined_loader.py", line 142, in __next__
    out = next(self.iterators[0])
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/dmri_pcconv/core/training.py", line 211, in __getitem__
    return self._get_patch_data(subject, local_index)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/dmri_pcconv/core/training.py", line 224, in _get_patch_data
    patch_in, patch_out = self.patcher.get_patch(
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/dmri_pcconv/core/patcher.py", line 87, in get_patch
    patch = self._patcher.get_patch(
RuntimeError: Fortran data order extraction not currently implemented.

**Comment by m-lyon** [comment]
The data you have saved in the data preprocessing step has Fortran ordering. The preprocessing pipeline cannot currently handle that so you will need to convert the data to C-contiguous ordering and resave the data. Here is how:

```python
import numpy as np

data = np.load('/path/to/data.npy') # Load the data that you saved in npy format
data_copy = data.copy(order='C') # Convert from Fortran ordering to C-contiguous
np.save('/path/to/data.npy', data_copy, allow_pickle=False) # Save this to disk as before
```

Let me know if there is anything else.

**Comment by caojiangege** [comment]
亲爱的教授：
  又报新的错误了

Epoch 0:   0%|                                          | 0/292 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/data_new/cj/dmri_pcconv/train2.py", line 62, in <module>
    trainer.fit(model, data_module)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 543, in fit
    call._call_and_handle_interrupt(
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 986, in _run
    results = self._run_stage()
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1030, in _run_stage
    self.fit_loop.run()
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/loops/fit_loop.py", line 205, in run
    self.advance()
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/loops/fit_loop.py", line 363, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 140, in run
    self.advance(data_fetcher)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 212, in advance
    batch, _, __ = next(data_fetcher)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/loops/fetchers.py", line 133, in __next__
    batch = super().__next__()
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/loops/fetchers.py", line 60, in __next__
    batch = next(self.iterator)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/utilities/combined_loader.py", line 341, in __next__
    out = next(self._iterator)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/lightning/pytorch/utilities/combined_loader.py", line 78, in __next__
    out[i] = next(self.iterators[i])
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/dmri_pcconv/core/training.py", line 211, in __getitem__
    return self._get_patch_data(subject, local_index)
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/dmri_pcconv/core/training.py", line 224, in _get_patch_data
    patch_in, patch_out = self.patcher.get_patch(
  File "/home/cj/.conda/envs/dmri-pcconv/lib/python3.9/site-packages/dmri_pcconv/core/patcher.py", line 87, in get_patch
    patch = self._patcher.get_patch(
RuntimeError: Max patch index: 2159, 3412 given.


进程已结束,退出代码1

**Comment by caojiangege** [comment]
亲爱的教授：
  这个是因为我的每个壳选的过多b值导致的吗？我现在选了各选了25个b1000,b2000,b3000。还是我的显卡不够 目前就1张GV100和一张3090

**Comment by m-lyon** [comment]
> 这个是因为我的每个壳选的过多b值导致的吗？我现在选了各选了25个b1000,b2000,b3000。还是我的显卡不够 目前就1张GV100和一张3090

Probably not. This seems like the issue has to do with the spatial dimensions of your data.

What is the shape of your data? Do all of the subjects have the same shape? Are you moving the angular dimension to the first dimension as mentioned in the readme?

**Comment by caojiangege** [comment]
训练已经没问题了，我想预测的时候还是出现了问题就是target_bvals和target_bvecs，我不知道如何生成，HCP只有data，mask,bvals,bvec这些在上面都已经用到了

**Comment by caojiangege** [comment]
import numpy as np
bvecs = np.random.randn(3, 10) # Here we're creating 10 random b-vectors
bvecs = bvecs / np.linalg.norm(bvecs, axis=0)这个是相当于他的bvecs输入吗？然后bvals和target_bvals是一样的

**Comment by m-lyon** [comment]
> 训练已经没问题了，我想预测的时候还是出现了问题就是target_bvals和target_bvecs，我不知道如何生成，HCP只有data，mask,bvals,bvec这些在上面都已经用到了

If you want to calculate some error statistics on your data, which I assume is the goal here, then you will want to split your data up into inputs (so input data, input bvecs, input bvals), and target data (target data, target bvals, and target bvecs). The model will then predict the target data given the input data and target bvecs and bvals. You can then compare how the predicted data and target data compare. 

For example, lets say you have 20 dMRI volumes (and 20 corresponding bvecs) - you could split that up into 10 for the input and 10 for the output.
